FROM ubuntu:latest 
#points to the latest LTS version

ENV FLUTTER_CHANNEL="stable"

# update all packages
RUN apt-get update -y && \
  apt-get upgrade -y

# core utils needed by flutter
RUN apt-get update && apt-get install -y \
  bash \
  curl \
  unzip \
  wget \
  xz-utils \
    && rm -rf /var/lib/apt/lists/*

####################
# FLUTTER 
####################
# flutter part based on https://docs.flutter.dev/get-started/install/linux
RUN apt-get update && apt-get install -y \
  file \
  git \
  libglu1-mesa \
  && rm -rf /var/lib/apt/lists/*
ENV FLUTTER_SDK_ROOT="/opt/flutter"
RUN mkdir -p ${FLUTTER_SDK_ROOT}

RUN git clone https://github.com/flutter/flutter.git ${FLUTTER_SDK_ROOT}

ENV PATH="${FLUTTER_SDK_ROOT}/bin:${FLUTTER_SDK_ROOT}/bin/cache/dart-sdk/bin:${PATH}"

RUN flutter config --enable-web
RUN flutter config --no-enable-linux-desktop
RUN flutter channel ${FLUTTER_CHANNEL}
RUN flutter precache
RUN flutter doctor
RUN flutter upgrade
RUN flutter --version